# Cloudflare Pages configuration
name = "pumptogether-website"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"
assets = { directory = ".open-next/assets", binding = "ASSETS" }
pages_build_output_dir = ".next"

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"